[streamlit_analytics2]
enabled = true

[storage]
save = true
type = "CSV"
save_to_json = "path/to/file.json"
load_from_json = "path/to/file.json"

[logs]
verbose = true

[access]
unsafe_password = "hunter2"

[firestore]
enabled = false
firestore_key_file = "firebase-key.json"
firestore_project_name = ""
firestore_collection_name = "streamlit_analytics2"
streamlit_secrets_firestore_key = ""

[session]
session_id = ""
